on:
  workflow_dispatch:

jobs:
  build_documentation:
    name: Building & uploading documentation.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Installing uv
        run: pip install uv

      - name: Installing Package
        run: uv sync --all-extras

      - name: Installing dependencies (Docs)
        run: sudo apt-get install graphviz

      - name: Building documentation
        run: |
          cd docs && uv run make clean html

      - name: Publishing documentation
        run: |
          uv run ghp-import -f -n -p docs/_build/html