name: Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  build_ui:
    name: Building UI
    runs-on: "ubuntu-24.04"

    steps:
      - uses: actions/checkout@v4.1.6

      - name: Installing Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Installing dependencies
        working-directory: chancy/plugins/api/ui
        run: npm install

      - name: Building UI
        working-directory: chancy/plugins/api/ui
        run: npm run build

  build:
    name: Running tests.

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        os: ["ubuntu-24.04", "macos-14"]
        pg: ["16", "17"]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v4.1.6

      - uses: ikalnytskyi/action-setup-postgres@v7
        with:
          username: postgres
          password: localtest
          database: postgres
          port: 8190
          postgres-version: ${{ matrix.pg }}
        id: postgres

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Installing uv
        run: pip install uv

      - name: Installing dependencies (Python)
        run: uv sync --all-extras

      - name: Running tests
        run: |
          uv run pytest -s -vvvvv --cov=chancy --cov-report=xml

      - name: Uploading coverage
        uses: codecov/codecov-action@v4
        with:
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          slug: TkTech/chancy

      - name: Installing dependencies (Docs)
        if: runner.os == 'ubuntu-latest'
        run: sudo apt-get install graphviz

      - name: Installing dependencies (Docs)
        if: runner.os == 'macos-latest'
        run: brew install graphviz

      - name: Building docs
        run: |
            cd docs && uv run make clean html